### ISSUE TITLE
Getting an error when installing.

### ISSUE THREAD

**Issue by ronnross** [splodingsocks/mochahq#3]
I'm using node 5.3.0, npm 3.3.12 on a mac. 

When I run `npm i mochahq -g` it fails when trying to do a `syscall chmod`. Here is the error that follows:
```
npm ERR! enoent ENOENT: no such file or directory, chmod '/Users/rr/.nvm/versions/node/v5.3.0/lib/node_modules/mochahq/server-dist/app.js'
```

Let me know if you need more information. Thanks.

**Comment by splodingsocks** [comment]
@ronnross thanks so much for reporting this. I hadn't included the babel-compiled output in the npm package. All should be well now.
