### ISSUE TITLE
empty dashboard

### ISSUE THREAD

**Issue by udisun** [splodingsocks/mochahq#7]
for some reason i'm seeing an empty dashboard.
mocha.opts file:
 --colors
 --compilers js:babel-core/register
 --require ./test/test_helper.js
 --reporter spec
 --ui bdd
 --prof
 --recursive

![image](https://cloud.githubusercontent.com/assets/950100/15375192/74ed3986-1d56-11e6-8dec-98f84c5450a8.png)

the terminal shows:
"a user connected"

running on chrome mac osx

**Comment by splodingsocks** [comment]
I've got to fix this, but t adding the directory where you tests are stored at the end of the opts file with no flags.

**Comment by splodingsocks** [comment]
@udisun Since it's been a while I'm going to assumed this worked for you and close the issue.
